/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WsTestImport } from './routes/wsTest'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as ProductsIndexImport } from './routes/products/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as CategoriesIndexImport } from './routes/categories/index'
import { Route as UsersNewImport } from './routes/users/new'
import { Route as ProductsNewImport } from './routes/products/new'
import { Route as LoginVerifyImport } from './routes/login/verify'
import { Route as CategoriesNewImport } from './routes/categories/new'
import { Route as UsersEditIdImport } from './routes/users/edit.$id'
import { Route as ProductsEditIdImport } from './routes/products/edit.$id'

// Create/Update Routes

const WsTestRoute = WsTestImport.update({
  id: '/wsTest',
  path: '/wsTest',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIndexRoute = ProductsIndexImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesIndexRoute = CategoriesIndexImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRoute,
} as any)

const UsersNewRoute = UsersNewImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRoute,
} as any)

const ProductsNewRoute = ProductsNewImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRoute,
} as any)

const LoginVerifyRoute = LoginVerifyImport.update({
  id: '/login/verify',
  path: '/login/verify',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesNewRoute = CategoriesNewImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => rootRoute,
} as any)

const UsersEditIdRoute = UsersEditIdImport.update({
  id: '/users/edit/$id',
  path: '/users/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const ProductsEditIdRoute = ProductsEditIdImport.update({
  id: '/products/edit/$id',
  path: '/products/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/wsTest': {
      id: '/wsTest'
      path: '/wsTest'
      fullPath: '/wsTest'
      preLoaderRoute: typeof WsTestImport
      parentRoute: typeof rootRoute
    }
    '/categories/new': {
      id: '/categories/new'
      path: '/categories/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof CategoriesNewImport
      parentRoute: typeof rootRoute
    }
    '/login/verify': {
      id: '/login/verify'
      path: '/login/verify'
      fullPath: '/login/verify'
      preLoaderRoute: typeof LoginVerifyImport
      parentRoute: typeof rootRoute
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewImport
      parentRoute: typeof rootRoute
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewImport
      parentRoute: typeof rootRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/edit/$id': {
      id: '/products/edit/$id'
      path: '/products/edit/$id'
      fullPath: '/products/edit/$id'
      preLoaderRoute: typeof ProductsEditIdImport
      parentRoute: typeof rootRoute
    }
    '/users/edit/$id': {
      id: '/users/edit/$id'
      path: '/users/edit/$id'
      fullPath: '/users/edit/$id'
      preLoaderRoute: typeof UsersEditIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wsTest': typeof WsTestRoute
  '/categories/new': typeof CategoriesNewRoute
  '/login/verify': typeof LoginVerifyRoute
  '/products/new': typeof ProductsNewRoute
  '/users/new': typeof UsersNewRoute
  '/categories': typeof CategoriesIndexRoute
  '/login': typeof LoginIndexRoute
  '/products': typeof ProductsIndexRoute
  '/users': typeof UsersIndexRoute
  '/products/edit/$id': typeof ProductsEditIdRoute
  '/users/edit/$id': typeof UsersEditIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wsTest': typeof WsTestRoute
  '/categories/new': typeof CategoriesNewRoute
  '/login/verify': typeof LoginVerifyRoute
  '/products/new': typeof ProductsNewRoute
  '/users/new': typeof UsersNewRoute
  '/categories': typeof CategoriesIndexRoute
  '/login': typeof LoginIndexRoute
  '/products': typeof ProductsIndexRoute
  '/users': typeof UsersIndexRoute
  '/products/edit/$id': typeof ProductsEditIdRoute
  '/users/edit/$id': typeof UsersEditIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/wsTest': typeof WsTestRoute
  '/categories/new': typeof CategoriesNewRoute
  '/login/verify': typeof LoginVerifyRoute
  '/products/new': typeof ProductsNewRoute
  '/users/new': typeof UsersNewRoute
  '/categories/': typeof CategoriesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/products/edit/$id': typeof ProductsEditIdRoute
  '/users/edit/$id': typeof UsersEditIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/wsTest'
    | '/categories/new'
    | '/login/verify'
    | '/products/new'
    | '/users/new'
    | '/categories'
    | '/login'
    | '/products'
    | '/users'
    | '/products/edit/$id'
    | '/users/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/wsTest'
    | '/categories/new'
    | '/login/verify'
    | '/products/new'
    | '/users/new'
    | '/categories'
    | '/login'
    | '/products'
    | '/users'
    | '/products/edit/$id'
    | '/users/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/wsTest'
    | '/categories/new'
    | '/login/verify'
    | '/products/new'
    | '/users/new'
    | '/categories/'
    | '/login/'
    | '/products/'
    | '/users/'
    | '/products/edit/$id'
    | '/users/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WsTestRoute: typeof WsTestRoute
  CategoriesNewRoute: typeof CategoriesNewRoute
  LoginVerifyRoute: typeof LoginVerifyRoute
  ProductsNewRoute: typeof ProductsNewRoute
  UsersNewRoute: typeof UsersNewRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ProductsEditIdRoute: typeof ProductsEditIdRoute
  UsersEditIdRoute: typeof UsersEditIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WsTestRoute: WsTestRoute,
  CategoriesNewRoute: CategoriesNewRoute,
  LoginVerifyRoute: LoginVerifyRoute,
  ProductsNewRoute: ProductsNewRoute,
  UsersNewRoute: UsersNewRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ProductsEditIdRoute: ProductsEditIdRoute,
  UsersEditIdRoute: UsersEditIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/wsTest",
        "/categories/new",
        "/login/verify",
        "/products/new",
        "/users/new",
        "/categories/",
        "/login/",
        "/products/",
        "/users/",
        "/products/edit/$id",
        "/users/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/wsTest": {
      "filePath": "wsTest.tsx"
    },
    "/categories/new": {
      "filePath": "categories/new.tsx"
    },
    "/login/verify": {
      "filePath": "login/verify.tsx"
    },
    "/products/new": {
      "filePath": "products/new.tsx"
    },
    "/users/new": {
      "filePath": "users/new.tsx"
    },
    "/categories/": {
      "filePath": "categories/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/products/": {
      "filePath": "products/index.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    },
    "/products/edit/$id": {
      "filePath": "products/edit.$id.tsx"
    },
    "/users/edit/$id": {
      "filePath": "users/edit.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
